// src/component/CharacterList.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  import { useCharacters } from "../model/store/characters";
  import { useAliases } from "../model/store/aliases";
  import { createCharacter, deleteCharacter } from "../model/service/CharacterService";
  import { useAuth } from "../model/store/auth";
  import { useUsers } from "../model/store/users";
  import { useRoom } from "../model/store/room";

  const { characters, } = useCharacters()
  const { aliases, } = useAliases()
  const { isLoggedIn } = useAuth()
  const { myUserId } = useUsers()
  const { roomId } = useRoom()

  const handleAddCharacter = async () => {
    console.log("CharacterList.handleAddCharacter");
    await createCharacter({
      owner: $myUserId,
      name: `character_${Date.now()}`,
      roomId: $roomId,
      text: "",
      activeAlias: "",
      imageId: "",
      showOnInitiative: true,
    })
  }

  const handleDeleteCharacter = async (characterId:string) => {
    console.log("CharacterList.handleDeleteCharacter");
    await deleteCharacter({
      characterId
    })
  }
</script>

<main>
  <h2>Character</h2>
  {#each $characters as c}
    <ul>
      <li>
      <button on:click={()=>{handleDeleteCharacter(c.id)}}>delete</button>
        {c.id},{c.name}</li>
    </ul>
  {/each}
  {#if $isLoggedIn}
    <button on:click={handleAddCharacter}>add character</button>
  {/if}
  <h2>Alias</h2>
  {#each $aliases as a}
    <ul>
      <li>{a.id},{a.name}</li>
    </ul>
  {/each}
</main>

// src/components/organisms/Float/FloatContents/CharacterList.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div style="width: 100%;height: 100%;overflow-y: scroll;">
    <ha-button @click="onClickCreateMyCharacter">キャラクタ追加</ha-button>
    <ha-input-form
      v-model="characterName"
      placeholder="キャラクタ名"
    ></ha-input-form>
    <CharacterListChip
      :key="characterId"
      v-for="characterId in characterIdList"
      :character-id="characterId"
    />
  </div>
</template>

<script>
import { FSCharacter } from "@/collections/Character";
import { FSPawn } from "@/collections/Pawn";
import HaButton from "@/components/atoms/HaButton";
import HaInputForm from "@/components/atoms/HaInputForm";
import CharacterListChip from "@/components/organisms/Float/FloatContents/CharacterListChip";

export default {
  name: "CharacterList",
  components: { CharacterListChip, HaInputForm, HaButton },
  data() {
    return {
      characterName: ""
    };
  },
  computed: {
    characterIdList() {
      return this.$store.getters["character/info"].map(c => c.id);
    }
  },
  methods: {
    async onClickCreateMyCharacter() {
      const characterName = this.characterName;
      const { id: userId, name: userName } = this.$store.getters["auth/user"];
      const roomId = this.$store.getters["room/info"].id;

      const t = Date.now() % 1000;

      const c = {
        owner: userId,
        name: characterName ?? `${userName}_c${t}`,
        roomId,
        imageId: null
      };
      await FSCharacter.Create(c);
    },
    async onClickActivateAlias(characterId, aliasId) {
      await FSCharacter.SetActiveAlias(characterId, aliasId);
    },
    async onClickDeletePawn(pawnId) {
      await FSPawn.Delete(pawnId);
    }
  }
};
</script>
