// src/component/float/ImageManager.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->
<script lang="ts">
  import ImageUploadButton from "../button/ImageUploadButton.svelte";
  import Checkbox from "../input/Checkbox.svelte";
  import { useImageSources } from "../../model/store/imageSources";
  import { Float } from "../../model/Float";
  import ImageTileSelector from "../image/ImageTileSelector.svelte";
  import { useUsers } from "../../model/store/users";
  import Button from "../button/Button.svelte";
  import { addTagImageSource, deleteImageSource, removeTagImageSource, updateImageSource } from "../../model/service/ImageSourceService";

  const { imageSources } = useImageSources()
  const { myUserId } = useUsers()

  export const float = {} as Float;

  let imageSourceId = ""
  let onlyMine = false
  let onlyMap = false
  let onlyCharacter = false
  let onlyUntagged = false
  $: imageSource = $imageSources.find(i => i.id === imageSourceId);
  $: filteredImageSources = $imageSources.filter(imgSrc => {
    if (onlyMine && imgSrc.owner !== $myUserId) {
      return false;
    }
    if (onlyMap && imgSrc.tags.indexOf('map') === -1) {
      return false;
    }
    if (onlyCharacter && imgSrc.tags.indexOf('character') === -1) {
      return false;
    }
    if (onlyUntagged && imgSrc.tags.length !== 0) {
      return false;
    }
    return true;
  });

  const whose = (imageSourceId: string) => {
    console.log(imageSourceId);
    return "tsrkzy"
  };
  const onMakeHidden = async (e: Event) => {
    console.log("ImageManager.onMakeHidden", e);
    if (!imageSourceId) {
      return
    }
    const currentTarget = e.currentTarget as HTMLInputElement;
    const hidden = currentTarget.checked
    await updateImageSource({ imageSourceId, criteria: { hidden } })
  }
  const onMakeMap = async (e: Event) => {
    console.log("ImageManager.onMakeMap", e);
    if (!imageSourceId) {
      return
    }
    const currentTarget = e.currentTarget as HTMLInputElement;
    const makeMap = currentTarget.checked
    if (makeMap) {
      await addTagImageSource({ imageSourceId, tag: 'map' })
    } else {
      await removeTagImageSource({ imageSourceId, tag: 'map' })
    }
  }
  const onMakeCharacter = async (e: Event) => {
    console.log("ImageManager.onMakeCharacter", e);
    if (!imageSourceId) {
      return
    }
    const currentTarget = e.currentTarget as HTMLInputElement;
    const makeCharacter = currentTarget.checked
    if (makeCharacter) {

      await addTagImageSource({ imageSourceId, tag: 'character' })
    } else {
      await removeTagImageSource({ imageSourceId, tag: 'character' })

    }
  }
  const onClickDeleteImageSource = async (e: Event) => {
    console.log("ImageManager.onClickDeleteImageSource", e);
    if (!imageSourceId) {
      return
    }
    await deleteImageSource(imageSourceId);
    imageSourceId = ""
  }
  const onChangeOnlyMine = (e: Event) => {
    console.log("ImageManager.onChangeOnlyMine", e);
    const currentTarget = e.currentTarget as HTMLInputElement;
    onlyMine = currentTarget.checked
  }
  const onChangeOnlyMap = (e: Event) => {
    console.log("ImageManager.onChangeOnlyMap", e);
    const currentTarget = e.currentTarget as HTMLInputElement;
    onlyMap = currentTarget.checked
  }
  const onChangeOnlyCharacter = (e: Event) => {
    console.log("ImageManager.onChangeOnlyCharacter", e);
    const currentTarget = e.currentTarget as HTMLInputElement;
    onlyCharacter = currentTarget.checked
  }
  const onChangeOnlyUntagged = (e: Event) => {
    console.log("ImageManager.onChangeOnlyUntagged", e);
    const currentTarget = e.currentTarget as HTMLInputElement;
    onlyUntagged = currentTarget.checked
  }
  const onChangeImageSource = (e: Event) => {
    console.log("ImageManager.onChangeImageSource", e);
    const currentTarget = e.currentTarget as HTMLInputElement;
    imageSourceId = currentTarget.value
  }
</script>

<ImageUploadButton></ImageUploadButton>
{imageSourceId}
{imageSource?.hidden}
{#if imageSourceId}
  <fieldset>
    <legend>画像の情報</legend>
    <ul>
      <li>
        <p>持ち主: { whose(imageSourceId) || "-" }</p>
      </li>
      <li>
        <Checkbox
            label="他のユーザから隠す"
            checked={!!(imageSource?.hidden)}
            onChange={(e)=>onMakeHidden(e)}
        ></Checkbox>
      </li>
      <li>
        <Checkbox
            label="#マップ"
            checked={imageSource?.tags.indexOf('map') !== -1}
            onChange={(e)=>onMakeMap(e)}
        ></Checkbox>
      </li>
      <li>
        <Checkbox
            label="#キャラクタ"
            checked={imageSource?.tags.indexOf('character') !== -1}
            onChange={(e)=>onMakeCharacter(e)}
        ></Checkbox>
      </li>
      <li>
        <Button handle={()=>onClickDeleteImageSource}>削除</Button>
      </li>
    </ul>
  </fieldset>
{/if}
<fieldset>
  <legend>フィルタ設定(AND)</legend>
  <ul>
    <li>
      <Checkbox
          label="自分の画像"
          checked={onlyMine}
          onChange={(e)=>onChangeOnlyMine(e)}
      ></Checkbox>
    </li>
    <li>
      <Checkbox
          label="#マップ"
          checked={onlyMap}
          onChange={(e)=>onChangeOnlyMap(e)}
          disabled={onlyUntagged}
      ></Checkbox>
    </li>
    <li>
      <Checkbox
          label="#キャラクタ"
          checked={onlyCharacter}
          onChange={(e)=>onChangeOnlyCharacter(e)}
          disabled={onlyUntagged}
      ></Checkbox>
    </li>
    <li>
      <Checkbox
          label="#タグなし"
          checked={onlyUntagged}
          onChange={(e)=>onChangeOnlyUntagged(e)}
      ></Checkbox>
    </li>
  </ul>
</fieldset>
<div class="image-source-tile__container">
  {#each filteredImageSources as imgSrc (imgSrc.id)}
    <ImageTileSelector
        imageSource={imgSrc}
        name={`image-source-manager_float-${float.id}`}
        checkedId={imageSourceId}
        onChange={(e)=>onChangeImageSource(e)}
    ></ImageTileSelector>
  {/each}
</div>

<style lang="scss">
  .image-source-tile__container {
    width: 100%;
    display: flex;
    flex-wrap: wrap;
  }
</style>

// src/components/organisms/Float/FloatContents/ImageManager.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div style="width: 100%; height: 100%; overflow-y: scroll">
    <input
      type="file"
      multiple
      accept="image/*"
      :value="inputFiles"
      @change="onClickFileUploadHandler"
    />
    <ha-checkbox
      label="削除ボタンを表示する"
      :value="deleteImageMode"
      @input="onClickDeleteMode"
    ></ha-checkbox>
    <fieldset v-show="image">
      <legend>画像の情報</legend>
      <ul v-if="isMine && imageId">
        <li>
          <p>持ち主: {{ whose(imageId) || "-" }}</p>
        </li>
        <li>
          <ha-checkbox
            label="他のユーザから隠す"
            :value="image.hidden"
            @input="onMakeHidden(imageId, $event)"
          ></ha-checkbox>
        </li>
        <li>
          <ha-checkbox
            :value="image.tags.indexOf('map') !== -1"
            label="#マップ"
            @input="onMakeMap(imageId, $event)"
          ></ha-checkbox>
        </li>
        <li>
          <ha-checkbox
            :value="image.tags.indexOf('character') !== -1"
            label="#キャラクタ"
            @input="onMakeCharacter(imageId, $event)"
          ></ha-checkbox>
        </li>
      </ul>
    </fieldset>
    <fieldset>
      <legend>フィルタ設定(AND)</legend>
      <ul>
        <li>
          <ha-checkbox
            label="自分の画像"
            @input="onChangeOnlyMine($event)"
          ></ha-checkbox>
        </li>
        <li>
          <ha-checkbox
            label="#マップ"
            @input="onChangeOnlyMap($event)"
            :disabled="onlyUntagged"
          ></ha-checkbox>
        </li>
        <li>
          <ha-checkbox
            label="#キャラクタ"
            @input="onChangeOnlyCharacter($event)"
            :disabled="onlyUntagged"
          ></ha-checkbox>
        </li>
        <li>
          <ha-checkbox
            label="#タグなし"
            @input="onChangeOnlyUntagged($event)"
          ></ha-checkbox>
        </li>
      </ul>
    </fieldset>
    <hr />
    <image-show-case
      :image-id="imageId"
      @selectImage="onChangeSelectedImage"
      :only-mine="onlyMine"
      :only-map="onlyMap"
      :only-character="onlyCharacter"
      :only-untagged="onlyUntagged"
      :delete-mode="deleteImageMode"
    ></image-show-case>
  </div>
</template>

<script>
import { FSImage } from "@/collections/Image";
import HaCheckbox from "@/components/atoms/HaCheckbox";
import ImageShowCase from "@/components/molecules/ImageShowCase";
export default {
  name: "ImageManager",
  components: { HaCheckbox, ImageShowCase },
  props: {
    floatId: {
      type: Number,
      require: true,
    },
  },
  data() {
    return {
      imageId: null,
      inputFiles: null,
      onlyMine: false,
      onlyMap: false,
      onlyCharacter: false,
      onlyUntagged: false,
      deleteImageMode: false,
    };
  },
  computed: {
    image() {
      return this.$store.getters["image/info"].find(
        (img) => img.id === this.imageId
      );
    },
    isMine() {
      return (
        this.image && this.image.owner === this.$store.getters["auth/user"].id
      );
    },
  },
  methods: {
    whose(imageId) {
      return FSImage.Whose(imageId);
    },
    onClickDeleteMode(e) {
      console.log("ImageManager.onClickDeleteMode");
      console.log(e); // @DELETEME
      this.deleteImageMode = e;
    },
    async onClickFileUploadHandler(e) {
      console.log("ImageManager.onClickFileUploadHandler"); // @DELETEME
      const { files = [] } = e.currentTarget;

      const promiseList = [];
      Array.prototype.forEach.call(files, (f) => {
        promiseList.push(FSImage.Create(f));
      });
      await Promise.all(promiseList);

      /* アップロードに成功したら空にする */
      this.inputFiles = null;
    },
    onChangeOnlyMine(v) {
      console.log("ImageManager.onChangeOnlyMine", v); // @DELETEME
      this.onlyMine = v;
    },
    onChangeOnlyMap(v) {
      console.log("ImageManager.onChangeOnlyMap", v);
      this.onlyMap = v;
    },
    onChangeOnlyCharacter(v) {
      console.log("ImageManager.onChangeOnlyCharacter", v);
      this.onlyCharacter = v;
    },
    onChangeOnlyUntagged(v) {
      console.log("ImageManager.onChangeOnlyUntagged", v);
      this.onlyUntagged = v;
    },
    onChangeSelectedImage(imageId) {
      console.log("ImageManager.onChangeSelectedImage", imageId); // @DELETEME
      this.imageId = imageId;
    },
    async onMakeHidden(imageId, value) {
      console.log("ImageManager.onMakeHidden", imageId, value); // @DELETEME
      await FSImage.Update(imageId, { hidden: value });
    },
    async onMakeMap(imageId, value) {
      console.log("ImageManager.onMakeMap"); // @DELETEME
      await FSImage.Tag(imageId, "map", value);
    },
    async onMakeCharacter(imageId, value) {
      console.log("ImageManager.onMakeCharacter"); // @DELETEME
      await FSImage.Tag(imageId, "character", value);
    },
  },
};
</script>

<style lang="scss" scoped></style>
