// src/component/float/NoteManager/NoteManager.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  import { useNotes } from "@/model/store/notes";
  import Button from "@/component/button/Button.svelte";
  import { yyyymmdd } from "@/util/helper";
  import { createNote, updateNote } from "@/model/service/NoteService";
  import { useRoom } from "@/model/store/room";

  const { notes } = useNotes()
  const { room } = useRoom()

  let noteId = $notes[0]?.id;

  $: note = $notes.find((note) => note.id === noteId)

  const onChangeSelect = (e: Event) => {
    const target = e.target as HTMLSelectElement
    noteId = target.value
  }

  const onClickCreateNote = async () => {
    console.log("NoteManager.onClickCreateNote");
    const t = yyyymmdd()
    const { id: newNoteId } = await createNote({
      room: $room.id,
      name: `新しい共有メモ_${t}`,
      text: ""
    })
    noteId = newNoteId
  }
  const onBlurNoteName = async (e: Event) => {
    console.log("NoteManager.onBlurNoteName");
    const target = e.target as HTMLInputElement
    const name = (target.value || "").trim();

    if (name === note?.name) {
      console.log("no changes");
      return
    }

    await updateNote({
      noteId,
      criteria: { name }
    })
  }
  const onBlurNoteText = async (e: Event) => {
    console.log("NoteManager.onBlurNoteText",);
    const target = e.target as HTMLTextAreaElement
    const text = target.value

    if (text === note?.text) {
      console.log("no changes");
      return
    }

    await updateNote({
      noteId,
      criteria: { text }
    })
  }
</script>

<select on:change={onChangeSelect}>
  <option selected={!noteId} disabled>選択してください</option>
  {#each $notes as note}
    <option value={note.id} selected={noteId === note.id}>{note.name}</option>
  {/each}
</select>
<Button handle={()=>onClickCreateNote()}>新規作成</Button>
<hr>
<input type="text" value={note?.name} on:blur={e=>onBlurNoteName(e)}>
<textarea value={note?.text} on:blur={e=>onBlurNoteText(e)}></textarea>

<style lang="scss">
  textarea {
    width: calc(100% - 1.0rem);
    height: 300px;
  }
</style>

// src/components/organisms/Float/FloatContents/NoteManager.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div style="width: 100%;height: 100%;overflow-y: scroll;">
    <ha-select
      :items="noteItems"
      mandatory
      :value="noteId"
      @change="onChangeNote($event)"
    ></ha-select>
    <ha-button @click="onCreateNote">追加</ha-button>
    <ha-input-form :value="name" @change="onChangeName($event)"></ha-input-form>
    <ha-textarea :value="text" @change="onChangeText($event)"></ha-textarea>
  </div>
</template>

<script>
import { FSNote } from "@/collections/Note";
import HaButton from "@/components/atoms/HaButton";
import HaInputForm from "@/components/atoms/HaInputForm";
import HaSelect from "@/components/atoms/HaSelect";
import HaTextarea from "@/components/atoms/HaTextarea";
export default {
  name: "NoteManager",
  components: { HaButton, HaInputForm, HaTextarea, HaSelect },
  props: {
    floatId: {
      type: Number,
      require: true
    }
  },
  data() {
    return {
      noteId: null,
      name: "",
      text: ""
    };
  },
  methods: {
    async onCreateNote() {
      const roomId = this.room?.id;
      const name = "新しいメモ";
      const text = "";
      const note = await FSNote.Create({ roomId, name, text });
      this.reloadNoteContent(note.id);
    },
    reloadNoteContent(noteId) {
      this.noteId = noteId;
      const { name, text } = this.notes.find(n => n.id === noteId);
      this.name = name;
      this.text = text;
    },
    onChangeNote(noteId) {
      this.reloadNoteContent(noteId);
    },
    async onChangeName(name) {
      this.name = name;
      await FSNote.Update(this.noteId, { name });
    },
    async onChangeText(text) {
      this.text = text;
      await FSNote.Update(this.noteId, { text });
    }
  },
  computed: {
    room() {
      return this.$store.getters["room/info"];
    },
    notes() {
      return this.$store.getters["note/info"];
    },
    noteItems() {
      return this.notes.map(n => ({ value: n.id, text: n.name }));
    }
  }
};
</script>

<style scoped></style>
