// src/components/organisms/TableView.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div>
    <ha-button @click="onClickDeleteTable">DELETE: {{ tableId }}</ha-button>
    <ha-button v-if="table" @click="onClickAddColumn">ADD INT COLUMN</ha-button>
    <ha-button v-if="table" @click="onClickAddColumn">ADD STR COLUMN</ha-button>
    <ha-button v-if="table" @click="onClickAddColumn"
      >ADD BOOL COLUMN</ha-button
    >
    <table v-if="table">
      <thead>
        <tr>
          <th v-for="c in table.columns" :key="c.id">
            {{ c.id }}:{{ c.label }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(character, i) in table.characters" :key="i">
          <td v-for="(r, j) in character" :key="j">
            <label>
              <input :type="r.inputType" :value="r.value" />
            </label>
          </td>
        </tr>
      </tbody>
    </table>
    <ha-button
      v-for="c in table.columns.filter(cc => !cc.id.startsWith('system'))"
      :key="c.id"
      @click="onClickDeleteColumn"
      >DROP COLUMN: {{ c.id }}:{{ c.label }}
    </ha-button>
  </div>
</template>
<script>
import { FSColumn } from "@/collections/Column";
import { FSTable } from "@/collections/Table";
import HaButton from "@/components/atoms/HaButton";

export default {
  name: "table-view",
  components: { HaButton },
  props: {
    tableId: { type: String, require: true }
  },
  methods: {
    async onClickDeleteTable(tableId) {
      await FSTable.Delete(tableId);
    },
    async onClickAddColumn(tableId, dataType) {
      const roomId = this.room.id;
      await FSColumn.Create({
        roomId,
        tableId,
        dataType,
        refPath: null,
        dataMap: {}
      });
    },
    async onClickDeleteColumn(columnId) {
      await FSColumn.Delete(columnId);
    }
  },
  computed: {
    room() {
      return this.$store.getters["room/info"];
    },
    table() {
      const matrixList = this.$store.getters["table/matrixList"];
      return matrixList.find(t => t.id === this.tableId);
    }
  }
};
</script>

// src/component/float/TableManager/TableView.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  import { useColumns } from "@/model/store/columns";
  import { useCharacters } from "@/model/store/characters";
  import { useRoom } from "@/model/store/room";
  import { type ColumnDataType, ColumnDataTypes } from "@/model/Column";
  import { Character } from "@/model/Character";

  export let tableId: string;

  const { columns: _columns } = useColumns();
  const { characters: _characters } = useCharacters();
  const { room } = useRoom();
  $: columns = $_columns.filter(c => c.table === tableId);
  $: characters = $_characters.filter(c => !c.archived && c.showOnInitiative);

  $: data = (() => {
    const roomId = $room.id;

    const colList: {
      id: string;
      system: boolean;
      roomId: string;
      label: string;
      dataType: ColumnDataType;
      refPath: string;
      dataMap: { [key: string]: string|number|boolean|null };
    }[] = [];
    const rowList: {
      characterId: string;
      cells: {
        columnId: string;
        system: boolean;
        characterId: string;
        value: string|number|boolean|null;
        dataType: ColumnDataType;
        refPath: string;
      }[];
    }[] = [];

    /* デフォルト列: character.idとcharacter.name */
    const idColumn = {
      id: "system_id",
      system: true,
      roomId,
      label: "#id",
      dataType: ColumnDataTypes.REF,
      refPath: "character.id",
      dataMap: {}
    };
    const nameColumn = {
      id: "system_name",
      system: true,
      roomId,
      label: "#name",
      dataType: ColumnDataTypes.REF,
      refPath: "character.name",
      dataMap: {},
    };
    colList.push(idColumn, nameColumn);
    for (let i = 0; i < columns.length; i++) {
      colList.push({
        system: false,
        id: columns[i].id,
        roomId: columns[i].room,
        label: columns[i].label,
        dataType: columns[i].dataType,
        refPath: columns[i].refPath,
        dataMap: columns[i].dataMap,
      });
    }

    /* キャラクタごとに行を作成 */
    for (let j = 0; j < characters.length; j++) {
      const character = characters[j];

      const row: {
        characterId: string, cells: {
          columnId: string;
          system: boolean;
          characterId: string;
          value: string|number|boolean|null;
          dataType: ColumnDataType;
          refPath: string;
        }[]
      } = {
        characterId: character.id,
        cells: [],
      };
      /* 列要素を作成 */
      for (let k = 0; k < colList.length; k++) {
        const {
          id,
          system = false,
          dataType,
          refPath,
          dataMap,
        } = colList[k];

        const cell: {
          columnId: string;
          system: boolean;
          characterId: string;
          value: string|number|boolean|null;
          dataType: ColumnDataType;
          refPath: string;
        } = {
          columnId: id,
          system,
          characterId: character.id,
          value: null,
          dataType,
          refPath,
        };
        if (dataType === ColumnDataTypes.REF) {
          /* characterの参照 */
          const field = refPath.split(".")[1];
          const c = characters.find((c) => c.id === character.id) as Character;
          if (field === "id") {

            cell.value = c.id;
          } else if (field === "name") {
            cell.value = c.name;
          } else {
            cell.value = "null";

          }
        } else {
          const _v = dataMap[character.id] as string|number|boolean|null;
          if (dataType === ColumnDataTypes.INT) {
            cell.value = parseInt(`${_v ?? 0}`, 10);
          } else if (dataType === ColumnDataTypes.STR) {
            cell.value = `${_v ?? ""}`;
          } else if (dataType === ColumnDataTypes.BOOL ) {
            cell.value = !!_v;
          }
        }
        row.cells.push(cell);
      }
      rowList.push(row);
    }

    return {
      columns: colList,
      rows: rowList,
    }
  })()
</script>

{#if tableId}
  <table>
    <thead>
    <tr>
      {#each data.columns as col (col.id)}
        <th>{col.label}</th>
      {/each}
    </tr>
    </thead>
    <tbody>
    {#each data.rows as column}
      <tr>
        {#each column.cells as cell (cell.columnId)}
          <td>{cell.value}</td>
        {/each}
      </tr>
    {/each}
    </tbody>
  </table>
{/if}
