// src/component/CharacterList.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  import { onDestroy } from "svelte";
  import { Character } from "../model/Character";
  import { useCharacters } from "../model/store/characters";

  const { subscribeCharacters } = useCharacters()

  $: characters = [] as Character[];
  const subscribes: (() => unknown)[] = [];
  subscribes.push(subscribeCharacters((_characters: Character[]) => {
    characters = _characters
  }))
  onDestroy(() => {
    subscribes.forEach(s => s());
  })
</script>

<main>
  {#each characters as c}
    <ul>
      <li>{c.Id},{c.Name}</li>
    </ul>
  {/each}
</main>

// src/components/organisms/FloatContents/CharacterList.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div>
    <ul>
      <li v-for="c in characterItems" :key="c.id">
        <span>{{ c.name }}</span
        ><ha-button>edit</ha-button>
      </li>
    </ul>
  </div>
</template>

<script>
import HaButton from "@/components/atoms/HaButton";
export default {
  name: "CharacterList",
  components: { HaButton },
  computed: {
    characterItems() {
      return this.$store.getters["character/info"].map(c => ({
        id: c.id,
        name: c.name
      }));
    }
  }
};
</script>

<style scoped></style>
