// src/component/input/ColorPicker.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  export let label: string;
  export let value: string;
  export let onChange: (e: Event) => void|Promise<void>;
</script>

<label>
  <input type="color" value={value}
         on:blur={(e)=>onChange(e)}>
  <span>{label}</span>
</label>

// src/components/organisms/FloatContents/ColorPicker.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2021.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <label>
    <span>文字色</span>
    <input type="color" :value="chatColor" @change="onChangeColor($event)" />
  </label>
</template>
<script>
export default {
  name: "color-picker",
  props: {
    chatColor: { type: String, require: true }
  },
  methods: {
    onChangeColor(e) {
      const color = e.currentTarget.value;
      this.$emit("change", color);
    }
  }
};
</script>
