// src/components/organisms/FloatContents/CharacterList.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div style="width: 100%;height: 100%;overflow-y: scroll;">
    <ha-button @click="onClickCreateMyCharacter">ADD MY CHARACTER</ha-button>
    <ha-select :items="characterItems"></ha-select>
    <ul>
      <li :key="item.id" v-for="item in characters">
        <span>{{ item.character.name }}({{ item.character.id }})</span>
        <ha-button>EDIT</ha-button>
        <ul>
          <li :key="a.id" v-for="a in item.aliases">
            <span>{{ a.name }}({{ a.id }})</span>
          </li>
        </ul>
        <ul>
          <li :key="p.id" v-for="p in item.pawns">
            <span>{{ p.id }} on ({{ p.transform }}) / {{ p.board }}</span>
          </li>
        </ul>
        <ha-button @click="onClickCreateAliasToCharacter(item.characterId)"
          >ADD ALIAS(→ OPEN ADD ALIAS WINDOW)
        </ha-button>
      </li>
    </ul>
  </div>
</template>

<script>
import { FSAlias } from "@/collections/Alias";
import { FSCharacter } from "@/collections/Character";
import HaButton from "@/components/atoms/HaButton";
import HaSelect from "@/components/atoms/HaSelect";

export default {
  name: "CharacterList",
  components: { HaSelect, HaButton },
  data() {
    return {
      imageSelect: null
    };
  },
  computed: {
    characters() {
      const characters = this.$store.getters["character/info"];
      const pawns = this.$store.getters["pawn/info"];
      const aliases = this.$store.getters["alias/info"];

      const items = [];
      for (let i = 0; i < characters.length; i++) {
        const c = characters[i];
        const item = {
          id: c.id,
          character: c,
          aliases: [],
          pawns: []
        };

        for (let j = 0; j < aliases.length; j++) {
          const a = aliases[j];
          const { character: characterId } = a;
          if (c.id === characterId) {
            item.aliases.push(a);
          }
        }

        for (let j = 0; j < pawns.length; j++) {
          const p = pawns[j];
          const { character: characterId } = p;
          if (c.id === characterId) {
            item.pawns.push(p);
          }
        }

        items.push(item);
      }
      return items;
    },
    characterItems() {
      const characters = this.$store.getters["character/info"];
      return characters
        .map(c => ({
          value: c.id,
          text: c.name
        }))
        .sort((a, b) => (a.text.toUpperCase() - b.text.toUpperCase() ? 1 : -1));
    }
  },
  methods: {
    async onClickCreateMyCharacter() {
      const { id: userId, name: userName } = this.$store.getters["auth/user"];
      const roomId = this.$store.getters["room/info"].id;
      const { imageSelect } = this;

      const t = Date.now() % 1000;

      const c = {
        owner: userId,
        name: `${userName}_c${t}`,
        roomId,
        imageId: imageSelect
      };
      await FSCharacter.Create(c);
    },
    async onClickCreateAliasToCharacter(characterId) {
      console.log("DebugIndicator.onClickCreateAliasToCharacter", characterId); // @DELETEME
      const character = this.$store.getters["character/tree"][characterId];

      const roomId = this.$store.getters["room/info"].id;
      const imageId = this.imageSelect;
      const t = Date.now() % 1000;
      const name = `${character.name}_a${t}`;
      const position = 1;
      const a = {
        roomId,
        characterId,
        imageId,
        name,
        position
      };

      await FSAlias.Create(a);
    }
  }
};
</script>

<style scoped></style>

// src/component/debug/CharacterList.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">
  import { useCharacters } from "@/model/store/characters";
  import { useAliases } from "@/model/store/aliases";
  import { createCharacter, deleteCharacter } from "@/model/service/CharacterService";
  import { useAuth } from "@/model/store/auth";
  import { useUsers } from "@/model/store/users";
  import { useRoom } from "@/model/store/room";

  export let open = false;

  const { characters, } = useCharacters()
  const { aliases, } = useAliases()
  const { isLoggedIn } = useAuth()
  const { myUserId } = useUsers()
  const { roomId } = useRoom()

  const handleAddCharacter = async () => {
    console.log("CharacterList.handleAddCharacter");
    await createCharacter({
      owner: $myUserId,
      name: `character_${Date.now()}`,
      roomId: $roomId,
      text: "",
      imageId: "",
      showOnInitiative: true,
    })
  }

  const handleDeleteCharacter = async (characterId: string) => {
    console.log("CharacterList.handleDeleteCharacter");
    await deleteCharacter({
      characterId
    })
  }
</script>

<main>
  <details {open}>
    <summary>Character</summary>
    {#each $characters as c}
      <ul>
        <li>
          <button on:click={()=>{handleDeleteCharacter(c.id)}}>delete</button>
          {c.id},{c.name}</li>
        {#each $aliases as a}
          {#if a.character === c.id}
            <ul>
              <li>{a.id},{a.name}</li>
            </ul>
          {/if}
        {/each}
      </ul>
    {/each}
    {#if $isLoggedIn}
      <button on:click={handleAddCharacter}>add character</button>
    {/if}
  </details>
</main>
