// src/component/chat/ChatLogViewer.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->
<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import { useChats } from "@/model/store/chats";
  import ChatRow from "@/component/chat/ChatRow.svelte";
  import { scrollChatToBottom } from "@/model/service/ChatService";
  import { ReadManager } from "@/model/ReadManager";
  import { get } from "svelte/store";
  import { getScrollParentClasses, } from "@/model/service/ChatService.js";

  export let floatId: number;

  const { chats } = useChats();

  // Chat一覧のfloatを開いた時点で最下部までスクロールするため、
  // その時点でのChatはすべて既読扱いにする
  ReadManager.New(get(chats).map(c => c.id));

  const SCROLL_OFFSET = 5;
  const PAGE_SIZE = 200;

  $: derivedChat = $chats.slice($chats.length - PAGE_SIZE, $chats.length);

  // /* スクロール位置が最下部からSCROLL_MARGIN px以内 */
  let onBottom = false;

  const subscribe = chats.subscribe(() => {
    if (onBottom) {
      tick().then(() => scrollChatToBottom(floatId))
    }
  })

  const onScrollChat = (e: Event) => {
    const target = e.target as HTMLDivElement;

    if (target.scrollTop + target.clientHeight >= target.scrollHeight - SCROLL_OFFSET) {
      onBottom = true;
    } else {
      onBottom = false;
    }
  };

  onMount(() => {
    tick().then(() => scrollChatToBottom(floatId))
  })

  onDestroy(() => {
    subscribe();
  })
</script>


<div class={getScrollParentClasses(floatId).join(" ")} on:scroll={onScrollChat}>
  <ol class="chat-log">
    {#each derivedChat as chat (chat.id)}
      <ChatRow {chat} floatId={floatId}/>
    {/each}
  </ol>
</div>

<style lang="scss">
  .scroll-parent {
    height: calc(100% - 107px);
    width: 100%;
    background-color: floralwhite;
    overflow-y: scroll;
    overflow-x: hidden;
  }

  ol.chat-log{
    padding: 0;
    margin: 0;
    list-style: none;
  }

</style>

// src/components/organisms/ChatLogViewer.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div
    :id="`chat-list--scroll-parent__${floatId}`"
    style="width: 100%;height: calc( 100% - 60px );background-color: white; overflow-y: scroll;overflow-x: hidden;"
  >
    <ol
      :id="`chat-list--scroll-content__${floatId}`"
      style="margin:0;padding: 0;"
    >
      <chat-row
        :float-id="floatId"
        :chat-id="c"
        v-for="c of chatIdList"
        :key="c"
      >
      </chat-row>
    </ol>
  </div>
</template>
<script>
import ChatRow from "@/components/organisms/ChatRow";

export default {
  name: "chat-log-viewer",
  components: { ChatRow },
  props: {
    floatId: { type: Number, require: true }
  },
  methods: {
    showNew() {
      const $parent = document.getElementById(
        `chat-list--scroll-parent__${this.floatId}`
      );
      $parent.scrollTo({
        top: $parent.scrollHeight - $parent.clientHeight,
        left: 0,
        behavior: "smooth"
      });
    }
  },
  computed: {
    chatIdList() {
      const chatList = this.$store.getters["chat/info"].map(c => c.id);
      return chatList.reverse();
    }
  },
  watch: {
    async chatIdList() {
      /* チャットが作成されるまで待機 */
      await this.$nextTick();
      this.showNew();
    }
  }
};
</script>
