// src/component/float/CharacterEdit.svelte
<!-----------------------------------------------------------------------------
  - Copyright (c) 2023.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<script lang="ts">

  import { useCharacters } from "../../model/store/characters";
  import { Float } from "../../model/Float";
  import { useAliases } from "../../model/store/aliases";
  import Button from "../button/Button.svelte";
  import { createAlias, deleteAlias, updateAlias } from "../../model/service/AliasService";
  import { useRoom } from "../../model/store/room";
  import { useImageSources } from "../../model/store/imageSources";
  import { updateCharacter } from "../../model/service/CharacterService";

  export let float: Float = {} as Float;

  const { characters } = useCharacters()
  const { aliases } = useAliases()
  const { room } = useRoom()
  const { imageSources } = useImageSources()

  $: floatId = float?.id;

  let characterId = float?.args?.characterId || "";
  $: character = $characters.find(c => c.id === characterId);
  $: characterName = character?.name || "";
  $: characterText = character?.text || "";
  $: isShowOnInitiative = !!(character?.showOnInitiative);
  $: characterColor = character?.color || "#000000";
  $: characterAliases = (() => {
    return $aliases.filter(a => a.character === characterId)
  })()
  $: aliasImageSources = (() => {
    return $imageSources.filter(i => characterAliases.some(a => a.image === i.id))
  })()

  let aliasIdSelected = character?.activeAlias;
  $: aliasSelected = characterAliases.find(a => a.id === character?.activeAlias);

  const getAliasImage = (imageId: string) => {
    return aliasImageSources.find(i => i.id === imageId)
  }

  const onChangeCharacter = async (e: Event) => {
    console.log("CharacterEdit.onChangeCharacter");
    const target = e.target as HTMLSelectElement;
    const _characterId = target.value;
    if (!_characterId) {
      return false;
    }
    characterId = _characterId;
  }

  const onBlurCharacterName = async (e: Event) => {
    console.log("CharacterEdit.onBlurCharacterName");
    const target = e.target as HTMLInputElement;
    const newCharacterName = target.value.trim();
    if (!newCharacterName) {
      target.value = characterName;
      return false;
    }
    await updateCharacter({ characterId, criteria: { name: newCharacterName } })
  }

  const onBlurCharacterText = async (e: Event) => {
    console.log("CharacterEdit.onBlurCharacterText");
    const target = e.target as HTMLTextAreaElement;
    const text = target.value.trim();
    if (text === characterText) {
      return false;
    }
    await updateCharacter({ characterId, criteria: { text } })
  }

  const onChangePawnSize = async (e: Event) => {
    console.log("CharacterEdit.onChangePawnSize");
    const target = e.target as HTMLSelectElement;
    const pawnSize = parseInt(target.value, 10);
    await updateCharacter({ characterId, criteria: { pawnSize } })
  }

  const onChangeCharacterShowOnInitiative = async (e: Event) => {
    console.log("CharacterEdit.onChangeCharacterShowOnInitiative");
    const target = e.target as HTMLInputElement;
    const showOnInitiative = !!(target.checked);
    await updateCharacter({ characterId, criteria: { showOnInitiative } })
  }

  const onChangeCharacterColor = async (e: Event) => {
    console.log("CharacterEdit.onChangeCharacterColor");
    const target = e.target as HTMLInputElement;
    const color = target.value || "#000000"
    console.log("target.value", target.value);
    await updateCharacter({ characterId, criteria: { color } })
  }

  const onChangeChatPosition = async (e: Event) => {
    console.log("CharacterEdit.onChangeChatPosition");
    const target = e.target as HTMLInputElement;
    const chatPosition = parseInt(target.value, 10);
    if (chatPosition === character?.chatPosition) {
      return false;
    }
    await updateCharacter({ characterId, criteria: { chatPosition } })
  }
  const onAddAlias = async (characterId: string) => {
    console.log("CharacterEdit.onAddAlias", characterId);
    await createAlias({
      roomId: $room.id,
      characterId,
      name: `立絵_${characterAliases.length + 1}`,
    })
  }

  export const onChangeActiveAlias = async (e: Event) => {
    console.log("CharacterEdit.onChangeActiveAlias");
    const target = e.target as HTMLInputElement;
    const activeAlias = target.value;
    await updateCharacter({ characterId, criteria: { activeAlias } })
  }

  const onClickDeleteAlias = async (aliasId: string) => {
    console.log("CharacterEdit.onClickDeleteAlias", aliasId);
    await deleteAlias({ aliasId })
  }

  const onBlurAliasName = async (e: Event, aliasId: string, aliasName: string) => {
    console.log("CharacterEdit.onBlurAliasName", aliasId);
    const target = e.target as HTMLInputElement;
    const name = target.value.trim();
    if (!name) {
      target.value = aliasName;
      return false;
    }
    await updateAlias({ aliasId, criteria: { name } })
  }

  const onChangeAlias = async (e: Event) => {
    console.log("CharacterEdit.onChangeAlias");
    const target = e.target as HTMLSelectElement;
    const _aliasId = target.value;
    if (!_aliasId) {
      return false;
    }
    aliasIdSelected = _aliasId;
  }

  const onChangeAliasImage = async (e: Event, aliasId: string|undefined) => {
    console.log("CharacterEdit.onChangeAliasImage");
    if (!aliasId) {
      return false;
    }
    const target = e.target as HTMLInputElement;
    const imageId = target.value;
    await updateAlias({ aliasId, criteria: { image: imageId } })
  }
</script>


<p>floatId: {floatId}</p>
<p>characterId: {characterId}</p>
<!-- キャラクター選択 -->
<select on:change={(e)=>onChangeCharacter(e)}>
  {#each $characters as c (c.id)}
    <option value={c.id} selected={c.id === character?.id}>{c.name}</option>
  {/each}
</select>
<fieldset>
  <legend>キャラクタの設定</legend>
  <div>
    <label>
      <span>名前</span>
      <input type="text" value={characterName}
             on:blur={(e)=>onBlurCharacterName(e)}>
    </label>
  </div>
  <div>
    <textarea
        placeholder="キャラクタ説明"
        value={characterText}
        on:blur={(e)=>onBlurCharacterText(e)}
    ></textarea>
  </div>
  <div>
    <label>
      <input
          type="checkbox"
          checked={isShowOnInitiative}
          on:change={(e)=>onChangeCharacterShowOnInitiative(e)}>
      <span>データテーブルに表示する</span>
    </label>
  </div>
  <div>
    <label>
      {characterColor}
      <input type="color" value={characterColor}
             on:change={(e)=>onChangeCharacterColor(e)}
      >
      <span>チャット色</span>
    </label>
  </div>
  <div>
    <label>
      <span>コマの大きさ</span>
      <select on:change={(e)=>onChangePawnSize(e)}>
        {#each [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as size}
          <option selected={character?.pawnSize === size} value={size}>x{size}</option>
        {/each}
      </select>
    </label>
  </div>
  <legend>立ち絵</legend>
  <div>
    <label>
      <span>表示位置</span>
      <input
          type="range"
          min="0"
          max="11"
          step="1"
          value={character?.chatPosition}
          on:change={(e)=>onChangeChatPosition(e)}
      >
    </label>
  </div>
  <div>
    <Button handle={()=>onAddAlias(characterId)}>立絵の追加</Button>
  </div>
  <div class="image-containter">
    {#each characterAliases as alias (alias.id)}
      <fieldset>
        <input
            type="text"
            value={alias.name}
            on:blur={(e)=>onBlurAliasName(e, alias.id, alias.name)}/>
        <div>
        <label>
          <input type="radio"
                 name={`active-alias-picker_float-${floatId}`}
                 value={alias.id}
                 checked={alias.id === character?.activeAlias}
                 on:change={(e)=>onChangeActiveAlias(e)}>
          <div class="alias-image__chip">
            {#if getAliasImage(alias.image)}
              <img src={getAliasImage(alias.image)?.url}
                   alt={alias.name}>
            {/if}
          </div>
        </label>
        </div>
        <Button handle={()=>onClickDeleteAlias(alias.id)}>削除</Button>
      </fieldset>
    {/each}
  </div>
</fieldset>
<fieldset>
  <select on:change={(e)=>onChangeAlias(e)}>
    {#each characterAliases as a (a.id)}
      <option value={a.id} selected={a.id === aliasIdSelected}>{a.name}</option>
    {/each}
  </select>

  <div class="image-chip__container">
    {aliasSelected?.image}
    {#each $imageSources as imgSrc (imgSrc.id)}
      <label>
        <input type="radio"
               name={`character-edit_alias-image_float-${floatId}`}
               value={imgSrc.id}
               checked={aliasSelected?.image===imgSrc.id}
               on:change={(e)=>onChangeAliasImage(e, aliasSelected?.id)}
        />
        <div class="alias-image__chip">
          <img src={imgSrc.url} alt={imgSrc.url}>
        </div>
      </label>
    {/each}
  </div>
</fieldset>

<style lang="scss">
  div.alias-image__chip {
    width: 48px;
    height: 48px;
    border: 1px solid #000000;

    & img {
      width: 100%;
      height: 100%;
    }
  }

  .image-chip__container {
    display: flex;
    flex-wrap: wrap;
  }

</style>

// src/components/organisms/Float/FloatContents/CharacterList/CharacterEdit.vue
<!-----------------------------------------------------------------------------
  - Copyright (c) 2020.                                                       -
  - @tsrkzy/Github.                                                           -
  - tsrmix@gmail.com                                                          -
  - All rights reserved.                                                      -
  ----------------------------------------------------------------------------->

<template>
  <div style="width: 100%;height: 100%;overflow-y: scroll;">
    <ha-select
      :value="characterId"
      :items="characterItemList"
      mandatory
      @change="onCharacterChange"
    ></ha-select>
    <fieldset>
      <legend>キャラクタの設定</legend>
      <div>
        <ha-input-form
          label="名前"
          :value="character['name']"
          @change="onCharacterNameInput"
        ></ha-input-form>
      </div>
      <div>
        <ha-textarea
          class="character-edit__textarea-wrapper"
          rows="3"
          :value="character['text']"
          placeholder="キャラクタ説明"
          @change="onCharacterTextInput"
          resizeable
        ></ha-textarea>
      </div>
      <div>
        <ha-checkbox
          label="データテーブルに表示する"
          :value="showOnInitiative"
          @change="onCharacterShowOnInitiative"
        ></ha-checkbox>
      </div>
      <div>
        <color-picker :chat-color="chatColor" @change="onChangeColor" />
      </div>
      <div>
        <ha-select
          label="コマの大きさ"
          :items="pawnSizeItems"
          v-model="pawnSizeStr"
          @change="onChangePawnSize"
        >
          <option disabled :value="null">select pawn size</option>
        </ha-select>
      </div>
      <ha-checkbox
        v-if="showDelete"
        v-model="showDeleteButton"
        label="キャラクタを完全に削除する"
      ></ha-checkbox>
      <ha-button v-if="showDeleteButton" @click="onDeleteCharacter"
        >キャラクタを削除</ha-button
      >
    </fieldset>
    <fieldset>
      <legend>立ち絵</legend>
      <div>
        <label>
          <span>表示位置</span>
          <input
            type="range"
            min="0"
            max="11"
            step="1"
            :value="chatPosition"
            @change="onChangePosition"
          />
        </label>
      </div>
      <div>
        <ha-button @click="onCreateAlias">立ち絵の追加</ha-button>
      </div>
      <ul style="padding-left: 0;margin: 0;">
        <li v-for="a in aliases" :key="a.id">
          <ha-input-form
            :value="a.name"
            @change="onAliasNameChange(a.id, $event)"
          ></ha-input-form>
        </li>
      </ul>
    </fieldset>
    <fieldset>
      <legend>画像の割り当て</legend>
      <div>
        <ha-select
          v-model="aliasId"
          :items="aliasItems"
          mandatory
          @change="onChangeAlias"
        >
          <option :value="null" selected disabled>割り当て先の立ち絵</option>
        </ha-select>
      </div>
      <div>
        <img
          v-if="aliasId"
          :src="srcUrl"
          :alt="imgAlt"
          style="max-width: 128px;max-height: 128px;"
        />
        <span v-else>立ち絵を選択してください</span>
      </div>
      <scroll-summary>
        <image-show-case
          :disabled="!aliasId"
          nav-to-image-manager
          v-model="imageId"
          @selectImage="onAliasImageChange"
        ></image-show-case>
      </scroll-summary>
    </fieldset>
  </div>
</template>

<script>
import { FSAlias } from "@/collections/Alias";
import { FSCharacter } from "@/collections/Character";
import { SYSTEM_COLOR } from "@/collections/Chat";
import { FSImage } from "@/collections/Image";
import HaButton from "@/components/atoms/HaButton";
import HaCheckbox from "@/components/atoms/HaCheckbox";
import HaInputForm from "@/components/atoms/HaInputForm";
import HaSelect from "@/components/atoms/HaSelect";
import HaTextarea from "@/components/atoms/HaTextarea";
import ImageShowCase from "@/components/molecules/ImageShowCase";
import ColorPicker from "@/components/molecules/ColorPicker";
import ScrollSummary from "@/components/atoms/ScrollSummary";
import { Smoke } from "@/scripts/Smoke";

const CHARACTER_NOT_SELECTED = "CHARACTER_NOT_SELECTED";

export default {
  name: "CharacterEdit",
  components: {
    HaButton,
    ColorPicker,
    ScrollSummary,
    HaCheckbox,
    HaSelect,
    ImageShowCase,
    HaTextarea,
    HaInputForm
  },
  props: {
    floatId: {
      type: Number,
      require: true
    }
  },
  data() {
    return {
      characterId: null,
      imageId: null,
      aliasId: null,
      srcUrl: null,
      imgAlt: null,
      chatPosition: "0",
      pawnSizeStr: "1",
      chatColor: SYSTEM_COLOR,
      showDeleteButton: false
    };
  },
  async created() {
    const float = this.$store.getters["float/info"].find(
      f => f.id === this.floatId
    );
    this.characterId = float?.args?.characterId ?? CHARACTER_NOT_SELECTED;
    this.syncAlias();

    const { image } = this.$store.getters["alias/info"].find(
      a => a.id === this.aliasId
    );

    if (!image) {
      console.warn(`no image on alias: ${this.aliasId}`);
    }
    await this.reloadImage(image);
  },
  methods: {
    async onCreateAlias() {
      const characterId = this.characterId;
      console.log("DebugIndicator.onClickCreateAliasToCharacter", characterId); // @DELETEME
      const character = this.$store.getters["character/info"].find(
        c => c.id === characterId
      );

      const roomId = this.$store.getters["room/info"].id;
      const t = Date.now() % 1000;
      const name = `${character.name}_a${t}`;
      const position = 1;
      const a = {
        roomId,
        characterId,
        imageId: null,
        name,
        position
      };

      await FSAlias.Create(a);
    },
    async onCharacterChange(characterId) {
      this.characterId = characterId;
      this.syncAlias();

      const { image } = this.$store.getters["alias/info"].find(
        a => a.id === this.aliasId
      );
      await this.reloadImage(image);
    },
    onCharacterNameInput(value) {
      console.log("CharacterEdit.onCharacterNameInput", value); // @DELETEME
      FSCharacter.Update(this.characterId, { name: value });
    },
    onCharacterTextInput(value) {
      console.log("CharacterEdit.onCharacterTextInput", value); // @DELETEME
      FSCharacter.Update(this.characterId, { text: value });
    },
    onCharacterShowOnInitiative(value) {
      console.log("CharacterEdit.onCharacterShowOnInitiative", value); // @DELETEME
      FSCharacter.Update(this.characterId, { showOnInitiative: value });
    },
    async onChangeColor(color) {
      console.log("CharacterEdit.onChangeColor", color); // @DELETEME
      this.chatColor = color;
      await FSCharacter.Update(this.characterId, { color });
    },
    async onChangePosition(e) {
      const chatPositionStr = e.currentTarget.value || "0";
      const chatPosition = parseInt(chatPositionStr, 10);
      await FSCharacter.Update(this.characterId, {
        chatPosition
      });
      this.chatPosition = chatPositionStr;
    },
    async onChangePawnSize(pawnSizeStr) {
      console.log("CharacterEdit.onChangePawnSize", pawnSizeStr); // @DELETEME
      await FSCharacter.Update(this.characterId, {
        pawnSize: parseInt(pawnSizeStr, 10)
      });
      this.pawnSizeStr = pawnSizeStr;
    },
    async onChangeAlias(aliasId) {
      const { image } = this.$store.getters["alias/info"].find(
        a => a.id === aliasId
      );
      await this.reloadImage(image);
    },
    async onAliasNameChange(aliasId, name) {
      console.log("CharacterEdit.onAliasNameChange", aliasId, name); // @DELETEME
      await FSAlias.Update(aliasId, { name });
    },
    async onAliasImageChange(imageId) {
      console.log("CharacterEdit.onAliasImageChange", imageId); // @DELETEME
      const { aliasId } = this;
      await FSAlias.SetImageId(aliasId, imageId);

      await this.reloadImage(imageId);
    },
    async reloadImage(imageId) {
      const image = await FSImage.GetById({ id: imageId });
      this.srcUrl = image ? image.url : "";
      this.imgAlt = image ? "" : "画像未設定";
      this.imageId = imageId;
    },
    syncAlias() {
      console.log("CharacterEdit.syncAlias"); // @DELETEME
      const {
        activeAlias = null,
        chatPosition = 0,
        pawnSize = 1,
        color = SYSTEM_COLOR
      } = this.$store.getters["character/info"].find(
        c => c.id === this.characterId
      );
      this.aliasId = activeAlias;
      this.chatPosition = `${chatPosition}`;
      this.pawnSizeStr = `${pawnSize}`;
      this.chatColor = color;
    },
    async onDeleteCharacter() {
      const characterId = this.characterId;
      await Smoke.on();
      await FSCharacter.Delete(characterId);
      await this.$store.dispatch("float/close", { id: this.floatId });
      await Smoke.off();
    }
  },
  computed: {
    characterItemList() {
      return this.$store.getters["character/info"].map(c => ({
        text: c.name,
        value: c.id
      }));
    },
    character() {
      return (
        this.$store.getters["character/info"].find(
          c => c.id === this.characterId
        ) || {}
      );
    },
    aliases() {
      return (
        this.$store.getters["alias/info"].filter(
          a => a.character === this.characterId
        ) || {}
      );
    },
    aliasItems() {
      return this.$store.getters["alias/info"]
        .filter(a => a.character === this.characterId)
        .map(a => ({
          value: a.id,
          text: a.name
        }));
    },
    pawnSizeItems() {
      const size = Array(10)
        .fill(0)
        .map((_, i) => i + 1);
      return size.map(i => ({ value: `${i}`, text: `x${i}` }));
    },
    showOnInitiative() {
      return !!this.character.showOnInitiative;
    },
    showDelete() {
      const owner = this.character?.owner;
      const myUserId = this.$store.getters["auth/user"].id;
      return owner === myUserId;
    }
  }
};
</script>
